kind: Service
apiVersion: v1
metadata:
  name: spring-boot-app
spec:
  selector:
    app: spring-boot-app
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  selector:
     matchLabels:
       app: spring-boot-app
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: knetsov91/spring-boot-rest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-host