name: Dev branch workflow

run-name: "${{ github.actor }} made ${{ github.event_name }} on ${{ github.head_ref || github.ref_name }}"

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name:  Build with Gradle
        run: ./gradlew build